# Generated by Django 3.1.5 on 2021-02-01 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20210131_1847'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='block',
        ),
        migrations.AddField(
            model_name='booking',
            name='block',
            field=models.ManyToManyField(related_name='bookings', to='events.EventBloсk'),
        ),
    ]
