# Generated by Django 3.1.5 on 2021-02-04 07:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0003_auto_20210201_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='users',
        ),
        migrations.AddField(
            model_name='booking',
            name='users',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='auth.user'),
            preserve_default=False,
        ),
    ]
