# Generated by Django 3.1.5 on 2021-02-07 02:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0006_auto_20210204_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='block',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.AddField(
            model_name='booking',
            name='blocks',
            field=models.ManyToManyField(related_name='bookings', to='events.EventBloсk'),
        ),
        migrations.AddField(
            model_name='booking',
            name='users',
            field=models.ManyToManyField(related_name='bookings', to=settings.AUTH_USER_MODEL),
        ),
    ]
